#
# Average distance between spawn attempts for Repurposed Structures Witch Huts.
# 1 for spawning in most chunks and 1001 for no spawn.
#Range: 1 ~ 1001
witchHutsOakMaxChunkDistance = 1001
#Range: 1 ~ 1001
witchHutsTaigaMaxChunkDistance = 1001
#Range: 1 ~ 1001
witchHutsGiantTreeTaigaMaxChunkDistance = 1001
#Range: 1 ~ 1001
witchHutsBirchMaxChunkDistance = 1001
#Range: 1 ~ 1001
witchHutsDarkForestMaxChunkDistance = 48

